[tableau]
token_name = "edtech_token"
token_secret = "10hQtCPeQhCGpwREVLnDSQ==:ScaRM4rR8k9e67EmgZg21PHxHyYqyZ1M"
server_url = "https://prod-apnortheast-a.online.tableau.com/#/site/courserecommendations/workbooks/472327/views"
site_id = "courserecommendations/workbooks/472327/views"  # in your site's URL behind the server_url